version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: eu-pescador-fishlog
    env_file: .env
    expose:
      - '4001'
    ports:
      - '4001:4001'
    command: bash -c "npm run migration:run  && npm run dev"
    depends_on:
      - db
  db:
    container_name: postgresDbLog
    image: "postgres:latest"
    restart: always
    volumes:
      - ./fishLog:/data/db
    command: postgres -c port=5434
    env_file: .env
    ports: 
      - '5434:5434'