INSERT INTO 
peixe (grande_grupo , grupo , nomes_comuns, nome_cientifico , familia , alimentacao , habitat , tamanho_max , peso_max , endemica , ameacada , piracema , introduzida , curiosidades , foto)
VALUES
('Peixes com escamas','Cachorras','Ueua  peixe-cachorro  Bicuda-branca','Acestrorhynchus falcatus','Acestrorhynchidae','Peixes','Grandes rios.','45',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Cachorras','Ueua  peixe-cachorro  Bicuda-branca','Acestrorhynchus microlepis','Acestrorhynchidae','Peixes','Grandes rios.','37','0.23','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Boca-larga  Fidalgo  Mandubé','Ageneiosus inermis','Auchenipteridae','Peixes','Rios com água corrente.','64.8','3.1','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Fidalgo  Mandubé-de-ferrão','Ageneiosus ucayalensis','Auchenipteridae','Peixes','Grandes rios.','64.8','3.1','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Peixes pequenos','Maiacá  Cruzador','Agoniates halecinus','Triportheidae','Peixes e invertebrados aquáticos.','Grandes rios.','26.8','115','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-chumbado  Rubinho','Aguarunichthys tocantinsensis','Pimelodidae','Desconhecida','Nos canais  de rios com água corrente.','31.7',' ','Endêmica do sistema Araguaia-Tocantins.','Sim. Categoria Vulnerável.','Sim','Não',' ','Sim'),
('Peixes com escamas','Piaus','Piau-vara','Anostomoides laticeps','Anostomidae','Material vegetal','Grandes rios.','30',' ','Não','Não','Sim','Não',' ','Sim'),
('Outros','Outros','Ituí-cavalo','Apteronotus camposdapazi','Apteronotidae','Invertebrados aquáticos.','Lagoas e lagos de água parada.',' ',' ','Sim','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes grandes','Pirarucu','Arapaima gigas','Arapaimidae','Peixes','Lagoas e lagos de água parada.','450','200','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Carás  Marianas e Jacundás','Oscar. Acará-açu','Astronotus ocelatus','Cichlidae','Peixes e invertebrados.','Lagoas e lagos de água parada.','45.7','1.6','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Lambarí-rabo-amarelo','Astyanax bimaculatus','Characidae','Insetos','Grandes rios.','17.5','96','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Lambarí-largo','Astyanax elachylepis','Characidae','Insetos','Riachos de água corrente.','11.4',' ','Sim','Não','Não','Não',' ',' '),
('Peixes com escamas','Lambarís e piabas','Lambarí-rabo-vermelho','Astyanax fasciatus','Characidae','Insetos','Rios com água corrente.','17.1','69','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Bagres pequenos','Carataí  Mapará  Olho-de-gato','Auchenipterus nuchalis','Auchenipteridae','Peixes e invertebrados aquáticos.','Grandes rios.','30',' ','Não','Não','Sim','Não',' ','Sim'),
('Cascudos','Cascudos pequenos','Cascudinho  limpa-pedras','Baryancistrus longipinnis','Loricariidae','Matéria orgânica em decomposição.','Fundo rochoso de riachos de corredeiras.','20',' ','Endêmica do sistema Araguaia-Tocantins.','Sim. Categoria Criticamente Ameaçada.','Não','Não',' ','Sim'),
('Cascudos','Cascudos pequenos','Cascudinho  limpa-pedras','Baryancistrus niveatus','Loricariidae','Matéria orgânica em decomposição.','Fundo rochoso de riachos de corredeiras.','34','0.52','Endêmica do sistema Araguaia-Tocantins.','Sim. Categoria Criticamente Ameaçada.','Não','Não',' ','Sim'),
('Peixes com escamas','Bicudas','Bicuda  Peixe-agulha','Boulengerella cuvieri','Ctenoluciidae','Peixes','Grandes rios.','88','6','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Bicudas','Bicuda  Peixe-agulha','Boulengerella maculata','Ctenoluciidae','Peixes','Grandes rios.','31.9',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Piraíba  Filhote','Brachiplatystoma filamentosum','Pimelodidae','Peixes','Grandes rios.','360','200','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Ladina','Brycon falcatus','Bryconidae','Peixes','Grandes rios.','37','1','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Piabanha  Matrinxã','Brycon gouldingi','Bryconidae','Peixes','Grandes rios.','47.8',' ','Sim','Sim. Categoria Ameaçada.','Sim','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Ladina','Brycon nattereri','Bryconidae','Peixes','Riachos de água corrente.','37',' ','Sim','Sim. Categoria Vulnerável.','Sim','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Piaba-beiradeira','Brycon pesu','Bryconidae','Peixes e insetos','Grandes rios.','12',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Ladina','Brycon polylepis','Bryconidae','Peixes','Riachos de água corrente.','22.4',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Piquirão','Bryconops alburnoides','Characidae','Insetos','Grandes rios.',' ',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piaus','Durinho  Cabeça-dura','Caenotropus labyrinthicus','Chilodontidae','Insetos','Grandes rios.','18.6',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Candirús','Candirú','Cetopsis candiru','Cetopsidae','Animais mortos','Grandes rios.','30',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Candirús','Candirú-açu','Cetopsis coecutiens','Cetopsidae','Animais mortos','Grandes rios.','27.3','280','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Peixes pequenos','Rabo-vermelho','Chalceus epakros','Chalceidae','Insetos','Grandes rios.','17.4','0.07','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Tucunarés','Tucunaré-amarelo','Cichla kelberi','Cichlidae','Peixes','Lagoas e lagos de água parada.','58.5','4.9','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Tucunarés','Tucunaré-azul','Cichla piquiti','Cichlidae','Peixes','Lagoas e lagos de água parada.','48','1.8','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Acará  Caroço-de-manga','Cichlasoma araguaiense','Cichlidae','Invertebrados aquáticos.','Lagoas e lagos de água parada.','22','0.3','Sim','Não','Não','Não',' ','Sim'),
('Outros','Baiacu','Baiacu','Colomesus tocantinensis','Tetraodontidae','Invertebrados aquáticos.','Lagoas e lagos de água parada.','10',' ','Sim','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Mariana  Jacundá-vermelho','Crenicichla lugubris','Cichlidae','Peixes','Lagoas e lagos de água parada.','32.9','0.44','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Carás  Marianas e Jacundás','Mariana  Jacundá-rajado','Crenicichla reticulata','Cichlidae','Peixes','Lagoas e lagos de água parada.','25',' ','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Carás  Marianas e Jacundás','Mariana  Jacundá-açú','Crenicichla sp','Cichlidae','Peixes','Lagoas e lagos de água parada.',' ',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Papa-terras e Curimatás','Branquinha','Curimata sp','Curimatidae','Matéria orgânica em decomposição.','Grandes rios.',' ',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Cachorras','Cachorra-icanga','Cynodon gibbus','Cynodontidae','Peixes','Grandes rios.','32.2','0.49','Não','Não','Sim','Não',' ',' '),
('Outros','Peixes elétricos','Poraquê. Peixe-elétrico','Electrophorus electricus','Gymnotidae','Peixes e invertebrados aquáticos.','Lagoas e lagos de água parada.','250','20','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes pequenos','Miguelinho','Exodon paradoxus','Characidae','Peixes','Grandes rios.','7.5',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Corró. Acará-bicudo','Geophagus aff. altifrons','Cichlidae','Peixes','Lagoas e lagos de água parada.','28',' ','Sim','Não','Não','Não',' ',' '),
('Outros','Outros','Tuvira','Gymnotus carapo','Gymnotidae','Invertebrados aquáticos.','Lagoas e lagos de água parada.','76','1.2','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-serra','Hassar wilderi','Doradidae','Invertebrados aquáticos.','Rios de água turva.','25',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Voador-rabo-vermelho','Hemiodus gracilis','Hemiodontidae','Onívoro','Grandes rios.','20','0.07','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Voador-escama-fina','Hemiodus microlepis','Hemiodontidae','Onívoro','Grandes rios.','27','161','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Voador-vermelho','Hemiodus ternetzi','Hemiodontidae','Onívoro','Grandes rios.',' ',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piabanha  Matrinxã e Voadores','Voador-escama-grossa','Hemiodus unimaculatus','Hemiodontidae','Onívoro','Grandes rios.','27','259','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Jeripoca  Jurupoca','Hemisorubim platyrhinchos','Pimelodidae','Peixes e invertebrados aquáticos.','Grandes rios.','61','2.7','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Acará-folha','Heros efasciatus','Cichlidae','Insetos','Lagoas e lagos de água parada.',' ',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Traíras','Jeju. Iuiú','Hoplerythrinus multitaeniatus','Erythrinidae','Peixes','Ambientes com água parada.','25',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Traíras','Traíra','Hoplias cf. malabaricus','Erythrinidae','Peixes','Ambientes com água parada.','65','3.8','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Traíras','Trairão','Hoplias curupira','Erythrinidae','Peixes','Ambientes com água parada.','35',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Cachorras','Cachorra-larga','Hydrolycus armatus','Cynodontidae','Peixes','Grandes rios.','89','8.5','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Cachorras','Cachorra-corcunda','Hydrolycus tatauaia','Cynodontidae','Peixes','Grandes rios.','59','2.7','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Mapará','Hypophthalmus edentatus','Pimelodidae','Filtrador (plâncton)','Grandes rios.','57.5','1.3','Não','Não','Sim','Sim',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Acará-roxo','Hypselacara temporalis','Cichlidae','Insetos','Lagoas e lagos de água parada.',' ',' ','Não','Não','Não','Não',' ','Sim'),
('Cascudos','Cascudos pequenos','Cascudo-paca','Leporacanthicus galaxias','Loricariidae','Matéria orgânica em decomposição.','Grandes rios.','25',' ','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Piaus','Piau-flamengo','Leporinus affinis','Anostomidae','Material vegetal','Grandes rios.','30',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piaus','Piau-comum','Leporinus friderici','Anostomidae','Material vegetal','Grandes rios.','40','1.5','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes pequenos','Sardinha-de-gato  Manjuba','Lycengraulis batesii','Engraulidae','Insetos','Grandes rios.','30',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Piaus','Piau-cabeça-gorda','Megaeporinus trifasciatus','Anostomidae','Material vegetal','Grandes rios.','45','2.2','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-prata','Megalonema platycephalum','Pimelodidae','Peixes e invertebrados aquáticos.','Grandes rios.','30',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Carás  Marianas e Jacundás','Acará-festivo','Mesonauta festivus','Cichlidae','Insetos','Lagoas e lagos de água parada.',' ','97','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Lambarí-rabo-preto-e-branco','Moenkhausia dichroura','Characidae','Insetos','Grandes rios.','12',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Lambarí-rabo-vermelho-e-preto','Moenkhausia lepidura','Characidae','Insetos','Grandes rios.','10.5',' ','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Lambarís e piabas','Lambarí-rabo-de-ouro','Moenkhausia oligolepis','Characidae','Insetos','Grandes rios.','12',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Pacú-dente-seco','Mylesinus paucisuquamatus','Serrasalmidae','Musgos aderidos às rochas das corredeiras.','Rios com corredeiras.','22',' ','Endêmica do sistema Araguaia-Tocantins.','Sim. Categoria Vulnerável.','Sim','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Pacú-dente-seco','Myleus setiger','Serrasalmidae','Material vegetal','Grandes rios.','30',' ','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Peixes redondos','Pacú-ferrado','Myloplus schomburgkii','Serrasalmidae','Material vegetal','Grandes rios.','42',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Pacú-branca','Myloplus torquatus','Serrasalmidae','Material vegetal','Grandes rios.',' ',' ','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Peixes redondos','Pacú-manteiga','Mylossoma duriventre','Serrasalmidae','Material vegetal','Grandes rios.','30','1','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Peixes médios','Tilápia','Oreochromis niloticus','Cichlidae','Matéria orgânica em decomposição.','Lagoas e lagos de água parada.','60','4.3','Não','Não','Não','Sim',' ',' '),
('Peixes com escamas','Peixes grandes','Aruanã','Osteoglossum bicirrhosum','Osteoglossidae','Peixes e invertebrados.','Lagoas e lagos de água parada.','90','6','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Cuiú-cuiú','Oxydoras niger','Doradidae','Invertebrados aquáticos.','Grandes rios.','120','23','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Corvinas','Corvina-amarela','Pachypops fourcroi','Scianidae','Peixes','Grandes rios.','25',' ','Não','Não','Sim','Não',' ','Sim'),
('Arraias','Arraias','Arraia-maçã. Aramaçá','Paratrygon aiereba','Potamotrygonidae','Peixes e invertebrados aquáticos.','Corredeiras dos grandes rios.','80','14','Endêmica da Amazônia.','Sim. Categoria Criticamente Ameaçada.','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes grandes','Apapá  Sardinhão  Pescada-amarela','Pellona castelnaeana','Pristigasteridae','Peixes','Grandes rios.','80','7.1','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes grandes','Pescada-branca','Pellona flavipinnis','Pristigasteridae','Peixes','Grandes rios.','80','7.1','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Pirarara','Phractocephalus hemioliopterus','Pimelodidae','Peixes','Grandes rios.','135','44.2','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Caranha  Pirapitinga','Piaractus brachypomus','Serrasalmidae','Frutas e sementes.','Grandes rios.','88','25','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Bagres pequenos','Chorão','Pimelodella cristata','Heptapteridae','Peixes e insetos','Grandes rios.','35',' ','Não','Não','Não','Não',' ',' '),
('Peixes de couro','Bagres pequenos','Chorão-de-faixa','Pimelodella gracilis','Heptapteridae','Peixes e insetos','Grandes rios.','20',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-moela','Pimelodina flavipinnis','Pimelodidae','Peixes e invertebrados aquáticos.','Canais de grandes rios.','39',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-amarelo  Mandí-cabeça-de-ferro','Pimelodus blochii','Pimelodidae','Peixes','Rios de água turva.','35',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Mandís','Mandí-guarú','Pimelodus ornatus','Pimelodidae','Peixes','Rios com água corrente.','35','426','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Barbado','Pinirampus pirinampu','Pimelodidae','Invertebrados aquáticos.','Grandes rios.','120','7.7','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Corvinas','Corvina','Plagioscion squamosissimus','Scianidae','Peixes','Grandes rios.','80','4.5','Não','Não','Não','Não','O osso na região do ouvido do peixe se chama otólito e é muito utilizado em estudos pois indica a idade do peixe e diversas outras informações.','Sim'),
('Peixes de couro','Bagres pequenos','Bacu-rebeca  Cascudo-rebeca  Cascudo listrado','Platydoras costatus','Doradidae','Invertebrados aquáticos.','Grandes rios.','30',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Coroatá  Piranambú. Surubim-de-corredeira','Platynematichthys notatus','Pimelodidae','Peixes','Rios com água corrente.','80',' ','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Lambarís e piabas','Lambarí-papudo','Poptella compressa','Characidae','Insetos','Grandes rios.','10.2',' ','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Bicudas','Bicuda-agulha','Potamorrhapis guianensis','Belonidae','Insetos','Remansos dos grandes rios.','29.1',' ','Não','Não','Não','Não',' ','Sim'),
('Arraias','Arraias','Arraia-de-fogo','Potamotrygon henlei','Potamotrygonidae','Peixes e invertebrados aquáticos.','Ambientes com água parada.','45',' ','Sim','Não','Não','Não',' ',' '),
('Arraias','Arraias','Arraia-carijó','Potamotrygon motoro','Potamotrygonidae','Peixes e invertebrados aquáticos.','Ambientes com água parada.','35','1.4','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Peixes médios','Papuda','Pristigaster cayana','Pristigasteridae','Insetos','Grandes rios.','14.5',' ','Não','Não','Não','Não',' ',' '),
('Peixes com escamas','Papa-terras e Curimatás','Papa-terra','Prochilodus nigricans','Prochilodontidae','Matéria orgânica em decomposição.','Grandes rios.','45','1.2','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Papa-terras e Curimatás','Branquinha-cascuda','Psectrogaster amazonica','Curimatidae','Matéria orgânica em decomposição.','Grandes rios.','19','0.2','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Surubim. Cachara  Pintado','Pseudoplatystoma fasciatum','Pimelodidae','Peixes','Grandes rios.','105','70','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Abotoado','Pterodoras granulosus','Doradidae','Peixes e frutas.','Grandes rios.','70','6.5','Não','Não','Sim','Não',' ',' '),
('Cascudos','Cascudos grandes','Cascudo-bodó. Acarí-bodó','Pterygoplichthys joselimaianus','Loricariidae','Matéria orgânica em decomposição.','Lagoas e lagos de água parada.','39.5',' ','Sim','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Piranha-vermelha','Pygocentrus nattereri','Serrasalmidae','Peixes','Grandes rios.','50','3.9','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Cachorras','Cachorra-facão','Raphiodon vulpinus','Cynodontidae','Peixes','Grandes rios.','80','2.1','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Jundiá  Bagre. Lobó','Rhamdia cf. quelen','Heptapteridae','Peixes','Riachos','47.4','4','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes médios','Tubarana  Tabarana','Salminus hilarii','Bryconidae','Peixes','Rios com corredeiras.','45','1.1','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Piaus','Piau-vara','Schizodon vittatus','Anostomidae','Material vegetal','Grandes rios.','35',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Papa-terras e Curimatás','Jaraqui','Semaprochilodus brama','Prochilodontidae','Invertebrados aquáticos.','Grandes rios.','54','2.6','Não','Não','Sim','Não',' ',' '),
('Peixes com escamas','Peixes redondos','Piranha','Serrasalmus eigenmanni','Serrasalmidae','Peixes','Grandes rios.','35','394','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Peixes redondos','Piranha-preta','Serrasalmus rhombeus','Serrasalmidae','Peixes','Grandes rios.','41.5','3','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Bagres médios','Bico-de-pato  Jurupensém','Sorubim lima','Pimelodidae','Peixes','Grandes rios.','54.2','1.3','Não','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Surubim-chicote. Bargada','Sorubimichthys planiceps','Pimelodidae','Peixes','Grandes rios.','150',' ','Não','Não','Sim','Não',' ','Sim'),
('Cascudos','Cascudos pequenos','Cascudo-chicote','Squaliforma emarginata','Loricariidae','Matéria orgânica em decomposição.','Grandes rios.','15',' ','Não','Não','Não','Não',' ','Sim'),
('Outros','Outros','Muçum','Synbranchus marmoratus','Synbranchidae','Invertebrados aquáticos.','Lagoas e lagos de água parada.','150',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Lambarís e piabas','Pataquinha','Tetragonopterus argenteus','Characidae','Insetos','Grandes rios.','12',' ','Não','Não','Não','Não',' ','Sim'),
('Peixes de couro','Bagres pequenos','Cangatí  Cachorro-do-padre','Trachelyopterus galeatus','Auchenipteridae','Peixes e invertebrados aquáticos.','Ambientes com água parada.','30','675','Não','Não','Não','Não',' ','Sim'),
('Peixes com escamas','Sardinhas','Sardinha-comprida','Triportheus albus','Triportheidae','Insetos','Grandes rios.','25.7','0.2','Não','Não','Sim','Não',' ','Sim'),
('Peixes com escamas','Sardinhas','Sardinha-papuda','Triportheus trifurcatus','Triportheidae','Insetos','Grandes rios.','16.5',' ','Sim','Não','Sim','Não',' ','Sim'),
('Peixes de couro','Grandes bagres','Jaú','Zungaro zungaro','Pimelodidae','Peixes','Grandes rios.','170','50','Não','Não','Sim','Não',' ','Sim'),
('Peixes de escama','Piaus','Tambiú. Piau-pintado','Leporellus vittatus','Anostomidae','Material vegetal','Grandes rios.','35',' ','Não','Não','Sim','Não',' ','Sim'),
('Peixes de escamas','Peixes redondos','Piranha-amarela','Serrasalmus maculatus','Serrasalmidae','Peixes','Grandes rios.','34.5','0.42','Não','Não','Sim','Não',' ','Sim'),
('Peixes de escamas','Piabanha  Voadores  Canivetes','Jatuarana','Argonectes robertsi','Hemiodontidae','Material vegetal','Grandes rios.','35.5','483','Não','Não','Sim','Não',' ','Sim');

